# permissions for end users to view simples.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: simple-viewer-role
rules:
- apiGroups:
  - example.lipovetsky.me
  resources:
  - simples
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.lipovetsky.me
  resources:
  - simples/status
  verbs:
  - get
