apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example
  labels:
    "app.kubernetes.io/managed-by": "failcontroller"
spec:
  ingressClassName: fooclass
  rules:
  - http:
      paths:
      - path: /testpath
        pathType: Prefix
        backend:
          serviceName: test
          servicePort: 80
